# Generated by Django 2.1.7 on 2019-02-16 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0002_auto_20190216_0922'),
        ('datasets', '0002_auto_20190216_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.IntegerField(choices=[(1, 'One Time Download'), (2, 'Unlimited Downloads')], default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.TextField()),
                ('expiration', models.DateField(blank=True, default=None, null=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datasets.Dataset')),
            ],
            options={
                'db_table': 'dataset_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ModelSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('PI', 'Per Inference'), ('PY', 'Per Year'), ('PM', 'Per Month')], default='PI', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.TextField()),
                ('expiration', models.DateField(blank=True, default=None, null=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Model')),
            ],
            options={
                'db_table': 'model_subscriptions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='modelsubscription',
            unique_together={('customer', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='datasetsubscription',
            unique_together={('customer', 'dataset')},
        ),
    ]
