# Generated by Django 2.1.7 on 2019-03-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetApiCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date_start', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dataset_api_calls',
            },
        ),
        migrations.CreateModel(
            name='ModelApiCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference_date_start', models.DateTimeField(auto_now_add=True)),
                ('process_time_ms', models.FloatField()),
            ],
            options={
                'db_table': 'model_api_calls',
            },
        ),
        migrations.AlterModelOptions(
            name='datasetsubscription',
            options={'ordering': ['date_subscribed']},
        ),
        migrations.AlterModelOptions(
            name='modelsubscription',
            options={'ordering': ['date_subscribed']},
        ),
        migrations.AddField(
            model_name='datasetsubscription',
            name='date_unsubscribed',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='modelsubscription',
            name='date_unsubscribed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='modelsubscription',
            name='subscription_type',
            field=models.CharField(choices=[('PI', 'Per Inference')], default='PI', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='datasetsubscription',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='modelsubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modelapicall',
            name='model_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.ModelSubscription'),
        ),
        migrations.AddField(
            model_name='datasetapicall',
            name='dataset_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.DatasetSubscription'),
        ),
        migrations.RemoveField(
            model_name='datasetsubscription',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='datasetsubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='datasetsubscription',
            name='url',
        ),
        migrations.RemoveField(
            model_name='modelsubscription',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='modelsubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='modelsubscription',
            name='url',
        ),
    ]
