# Generated by Django 2.1.7 on 2019-03-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190310_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetsubscription',
            options={'ordering': ['-date_subscribed']},
        ),
        migrations.AlterModelOptions(
            name='modelsubscription',
            options={'ordering': ['-date_subscribed']},
        ),
    ]
