# Generated by Django 2.2 on 2019-07-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20190328_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelapicall',
            name='process_time_ms',
            field=models.FloatField(default=0.3228274445067466),
        ),
    ]
