# Generated by Django 2.1.7 on 2019-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_model_views'),
        ('datasets', '0002_auto_20190216_0922'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosuser',
            name='dataset_bookmarks',
            field=models.ManyToManyField(to='datasets.Dataset'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='model_bookmarks',
            field=models.ManyToManyField(to='models.Model'),
        ),
    ]
