# Generated by Django 2.2.2 on 2019-07-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190307_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosuser',
            options={},
        ),
        migrations.AddField(
            model_name='datosuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='company',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='datosuser',
            unique_together={('email',)},
        ),
    ]
