# Generated by Django 2.1.7 on 2019-03-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20190225_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
