# Generated by Django 2.2.2 on 2019-06-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_model_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='weights_path',
        ),
        migrations.AddField(
            model_name='model',
            name='third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='model',
            name='version',
            field=models.TextField(blank=True, default=''),
        ),
    ]
