# Generated by Django 2.1.7 on 2019-03-28 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0003_auto_20190328_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelBillCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start', models.DateTimeField(auto_now_add=True)),
                ('cycle_end', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='modelbill',
            name='bill_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='billing.ModelBillCycle'),
        ),
        migrations.AddField(
            model_name='modelbill',
            name='model_api_call_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.ModelApiCall'),
        ),
    ]
