# Generated by Django 2.1.7 on 2019-02-16 16:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_auto_20190216_0922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0002_auto_20190216_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField(blank=True, default='')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('original_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datasets.Dataset')),
            ],
            options={
                'db_table': 'dataset_reviews',
            },
        ),
        migrations.CreateModel(
            name='ModelReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField(blank=True, default='')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('original_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Model')),
            ],
            options={
                'db_table': 'model_reviews',
            },
        ),
        migrations.AlterUniqueTogether(
            name='modelreview',
            unique_together={('author', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='datasetreview',
            unique_together={('author', 'dataset')},
        ),
    ]
