# Generated by Django 2.2 on 2019-07-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetreview',
            options={'ordering': ['last_modified']},
        ),
        migrations.AlterModelOptions(
            name='modelreview',
            options={'ordering': ['-last_modified']},
        ),
    ]
